"use client";
import { useEffect, useRef, useState } from "react";
import { AnimatePresence, motion, useReducedMotion } from "motion/react";
import { ArrowDown, ArrowUpRight, Check, ChevronRight, Code2, ExternalLink, Github, Linkedin, Mail, MapPin, Menu, X, Terminal, Sparkles, ShieldCheck, Layers3, GraduationCap, Trophy } from "lucide-react";
import { certifications, education, profile, projects, skills } from "@/lib/data";

function Reveal({children,className="",delay=0}:{children:React.ReactNode;className?:string;delay?:number}){const reduce=useReducedMotion();return <motion.div className={className} initial={reduce?false:{opacity:0,y:24}} whileInView={reduce?undefined:{opacity:1,y:0}} viewport={{once:true,margin:"-70px"}} transition={{duration:.65,delay,ease:[.22,1,.36,1]}}>{children}</motion.div>}

export default function Site(){
 const [active,setActive]=useState<typeof projects[number]|null>(null); const [menu,setMenu]=useState(false); const [spot,setSpot]=useState({x:-500,y:-500}); const reduce=useReducedMotion();
 useEffect(()=>{const move=(e:MouseEvent)=>setSpot({x:e.clientX,y:e.clientY});window.addEventListener("mousemove",move);return()=>window.removeEventListener("mousemove",move)},[]);
 useEffect(()=>{if(!reduce){import("@studio-freight/lenis").then(({default:Lenis})=>{const lenis=new Lenis({duration:1.05,easing:(t:number)=>Math.min(1,1.001-Math.pow(2,-10*t))});let raf=(t:number)=>{lenis.raf(t);requestAnimationFrame(raf)};requestAnimationFrame(raf);return()=>lenis.destroy()})}},[reduce]);
 const nav=["about","skills","projects","workflow","education","contact"];
 return <>
  <div className="cursor-spot" style={{left:spot.x,top:spot.y}} aria-hidden />
  <header className="fixed top-0 left-0 right-0 z-40 border-b border-white/5 bg-[#08090b]/80 backdrop-blur-xl"><div className="container h-18 flex items-center justify-between">
   <a href="#top" className="font-semibold tracking-[-.03em]">AV<span className="text-white/35">/</span></a>
   <nav className="hidden md:flex items-center gap-7 text-[12px] text-white/55">{nav.map(n=><a key={n} className="hover:text-white transition-colors" href={`#${n}`}>{n}</a>)}</nav>
   <a href="#contact" className="hidden md:flex items-center gap-2 text-[12px] border border-white/10 px-4 py-2 rounded-full hover:bg-white hover:text-black transition-colors">Let's connect <ArrowUpRight size={14}/></a>
   <button aria-label="Toggle menu" onClick={()=>setMenu(v=>!v)} className="md:hidden p-2">{menu?<X size={20}/>:<Menu size={20}/>}</button>
  </div>{menu&&<div className="md:hidden border-t border-white/5 bg-[#08090b] px-5 py-5 space-y-4">{nav.map(n=><a onClick={()=>setMenu(false)} className="block text-white/65" key={n} href={`#${n}`}>{n}</a>)}</div>}</header>

  <main id="top">
   <section className="relative min-h-screen flex items-center overflow-hidden pt-24"><div className="absolute inset-0 grid-bg"/><div className="container relative z-10 py-28">
    <Reveal><div className="flex items-center gap-3 text-[11px] uppercase tracking-[.2em] text-white/45"><span className="h-px w-8 bg-white/30"/> Available for opportunities</div></Reveal>
    <Reveal delay={.08}><h1 className="mt-7 max-w-5xl text-[clamp(3.6rem,9vw,8.4rem)] leading-[.86] tracking-[-.075em] font-semibold">I build digital<br/><span className="text-white/30">systems that matter.</span></h1></Reveal>
    <Reveal delay={.15}><p className="mt-9 max-w-2xl text-base md:text-lg leading-8 text-white/55">{profile.summary}</p></Reveal>
    <Reveal delay={.22}><div className="mt-9 flex flex-wrap gap-3"><a href="#projects" className="group inline-flex items-center gap-3 rounded-full bg-white text-black px-5 py-3 text-sm font-medium hover:gap-4 transition-all">Explore work <ArrowDown size={15}/></a><a href={`mailto:${profile.email}`} className="inline-flex items-center gap-2 rounded-full border border-white/10 px-5 py-3 text-sm text-white/75 hover:border-white/25 hover:text-white transition">Contact me <Mail size={15}/></a></div></Reveal>
    <div className="absolute bottom-9 left-0 right-0 container flex items-end justify-between text-[10px] uppercase tracking-[.18em] text-white/30"><span>Software Developer · Full Stack · Backend</span><span className="hidden sm:flex items-center gap-2">Scroll <ArrowDown size={12}/></span></div>
   </div></section>

   <section id="about" className="border-t border-white/7 py-28 md:py-36"><div className="container grid md:grid-cols-[.7fr_1.3fr] gap-12 md:gap-24"><Reveal><p className="text-xs uppercase tracking-[.2em] text-white/35">01 / About</p></Reveal><Reveal delay={.08}><div><h2 className="text-3xl md:text-5xl leading-tight tracking-[-.045em] font-medium">Engineer first. Curious by default. <span className="text-white/35">Focused on turning ideas into useful products.</span></h2><p className="mt-8 text-white/55 leading-8 max-w-2xl">I’m a B.Tech Computer Science & Engineering student with hands-on full-stack experience through MERN applications and an internship at InternPay. Alongside web development, I build Java applications using OOP, Collections, Streams, layered architecture and design patterns.</p><div className="mt-10 grid grid-cols-2 sm:grid-cols-3 gap-3">{[["01","MERN stack"],["02","Java + DSA"],["03","Backend APIs"],["04","Secure auth"],["05","Clean architecture"],["06","Problem solving"]].map(([n,t])=><div key={n} className="border border-white/8 rounded-xl p-4 bg-white/[.015]"><span className="text-[10px] text-white/25">{n}</span><p className="mt-5 text-sm text-white/75">{t}</p></div>)}</div></div></Reveal></div></section>

   <section id="skills" className="border-t border-white/7 py-28"><div className="container"><Reveal><p className="text-xs uppercase tracking-[.2em] text-white/35">02 / Technical skills</p><h2 className="mt-4 text-3xl md:text-5xl tracking-[-.04em]">Tools I use to build.</h2></Reveal><div className="mt-14 grid md:grid-cols-2 lg:grid-cols-4 gap-px bg-white/8 border border-white/8">{skills.map((s,i)=><Reveal key={s.group} delay={i*.03}><div className="h-full bg-[#08090b] p-6"><p className="text-[11px] uppercase tracking-[.16em] text-white/35">{s.group}</p><div className="mt-5 flex flex-wrap gap-2">{s.items.map(x=><span key={x} className="rounded-full border border-white/9 px-3 py-1.5 text-xs text-white/70">{x}</span>)}</div></div></Reveal>)}</div></div></section>

   <section id="projects" className="border-t border-white/7 py-28"><div className="container"><Reveal><div className="flex items-end justify-between"><div><p className="text-xs uppercase tracking-[.2em] text-white/35">03 / Selected work</p><h2 className="mt-4 text-3xl md:text-5xl tracking-[-.04em]">Projects with a purpose.</h2></div><span className="hidden md:block text-xs text-white/30">{String(projects.length).padStart(2,"0")} builds</span></div></Reveal><div className="mt-14 border-t border-white/10">{projects.map((p,i)=><motion.button key={p.id} onClick={()=>setActive(p)} whileHover={reduce?{}:{x:8}} className="w-full text-left group border-b border-white/10 py-8 md:py-10 flex items-start gap-5 md:gap-8 focus-visible:outline focus-visible:outline-2 focus-visible:outline-white"><span className="text-xs text-white/25 pt-2">{p.number}</span><div className="flex-1"><div className="flex flex-wrap items-center gap-3"><h3 className="text-2xl md:text-4xl tracking-[-.04em] group-hover:text-white transition">{p.name}</h3><span className="text-[10px] uppercase tracking-[.16em] text-white/30 border border-white/8 rounded-full px-2.5 py-1">{p.label}</span></div><p className="mt-3 max-w-2xl text-sm md:text-base text-white/45 leading-7">{p.description}</p><div className="mt-5 flex flex-wrap gap-2">{p.stack.slice(0,5).map(t=><span key={t} className="text-[11px] text-white/35">{t}</span>)}</div></div><ChevronRight className="mt-2 text-white/25 group-hover:text-white transition" size={22}/></motion.button>)}</div></div></section>

   <section id="workflow" className="border-t border-white/7 py-28"><div className="container grid lg:grid-cols-[.75fr_1.25fr] gap-14"><Reveal><p className="text-xs uppercase tracking-[.2em] text-white/35">04 / Development workflow</p><h2 className="mt-4 text-3xl md:text-5xl tracking-[-.04em]">From idea to reliable software.</h2></Reveal><div className="space-y-0">{["Idea","Prototype","Development","Debugging","Testing","Documentation","Deployment"].map((x,i)=><Reveal key={x} delay={i*.04}><div className="border-b border-white/8 py-5 flex items-center gap-5"><span className="font-mono text-[11px] text-white/25">0{i+1}</span><span className="text-lg text-white/80">{x}</span><span className="ml-auto text-white/20">→</span></div></Reveal>)}</div></div></section>

   <section className="border-t border-white/7 py-28"><div className="container grid lg:grid-cols-[.7fr_1.3fr] gap-14"><Reveal><p className="text-xs uppercase tracking-[.2em] text-white/35">05 / AI-assisted development</p><div className="mt-6 flex h-12 w-12 items-center justify-center rounded-xl border border-white/10"><Sparkles size={20}/></div></Reveal><Reveal delay={.08}><div><h2 className="text-3xl md:text-5xl tracking-[-.04em]">AI as leverage, not a substitute.</h2><p className="mt-7 max-w-2xl text-white/55 leading-8">My resume reflects AI-enabled application development through BRAIN CODE, including scope for personalized learning and intelligent recommendations. I treat AI-assisted development as a productivity layer around engineering fundamentals: understanding the problem, validating the output, debugging, testing and owning the final implementation.</p><div className="mt-9 flex flex-wrap gap-2">{["Context","Prototype","Implement","Validate","Debug","Test","Document"].map((x,i)=><span key={x} className="inline-flex items-center gap-2 rounded-full border border-white/9 px-3 py-2 text-xs text-white/60"><Check size={12}/>{x}</span>)}</div></div></Reveal></div></section>

   <section id="education" className="border-t border-white/7 py-28"><div className="container"><Reveal><p className="text-xs uppercase tracking-[.2em] text-white/35">06 / Education & credentials</p></Reveal><div className="mt-12 grid lg:grid-cols-2 gap-12"><Reveal><div className="flex gap-5"><GraduationCap className="text-white/40 shrink-0"/><div><p className="text-xl">{education[0].school}</p><p className="mt-2 text-white/55">{education[0].degree}</p><p className="mt-4 text-xs text-white/30">{education[0].period} · {education[0].location}</p><p className="mt-2 text-sm text-white/70">{education[0].result}</p></div></div><div className="mt-10 flex gap-5"><GraduationCap className="text-white/40 shrink-0"/><div><p className="text-lg">{education[1].school}</p><p className="mt-2 text-white/55">{education[1].degree}</p><p className="mt-4 text-xs text-white/30">{education[1].period} · {education[1].location}</p><p className="mt-2 text-sm text-white/70">{education[1].result}</p></div></div></Reveal><Reveal delay={.1}><div><p className="text-xs uppercase tracking-[.16em] text-white/30">Certifications</p><div className="mt-5 space-y-3">{certifications.map(c=><div key={c} className="border border-white/8 rounded-xl p-5 flex items-center gap-3"><ShieldCheck size={17} className="text-white/40"/><span className="text-sm text-white/70">{c}</span></div>)}</div><div className="mt-10"><p className="text-xs uppercase tracking-[.16em] text-white/30">Achievements</p><div className="mt-5 space-y-3"><div className="flex gap-3 text-sm text-white/60"><Trophy size={16} className="shrink-0 text-white/35"/>Participated in 2 college-level hackathons.</div><div className="flex gap-3 text-sm text-white/60"><Trophy size={16} className="shrink-0 text-white/35"/>Won multiple awards in Poetry, Speech, and Debate competitions.</div></div></div></div></Reveal></div></div></section>

   <section className="border-t border-white/7 py-28"><div className="container"><Reveal><div className="border border-white/8 rounded-2xl p-7 md:p-10 bg-white/[.015] grid md:grid-cols-[auto_1fr_auto] items-center gap-6"><div className="flex h-12 w-12 items-center justify-center rounded-xl border border-white/8"><Github size={21}/></div><div><p className="text-xl">GitHub / Open-source work</p><p className="mt-1 text-sm text-white/45">Repository details were not included in the supplied resume, so this portfolio does not invent repository names or stats.</p></div><span className="text-xs text-white/30">Add verified repos when available</span></div></Reveal></div></section>

   <section id="contact" className="border-t border-white/7 py-32"><div className="container text-center"><Reveal><p className="text-xs uppercase tracking-[.2em] text-white/35">07 / Contact</p><h2 className="mt-5 text-[clamp(3rem,7vw,7rem)] leading-[.9] tracking-[-.07em] font-semibold">Let’s build<br/><span className="text-white/30">something useful.</span></h2><p className="mt-8 text-white/45">Open to full-stack, backend and software development opportunities.</p><a href={`mailto:${profile.email}`} className="mt-9 inline-flex items-center gap-3 rounded-full bg-white text-black px-6 py-3 font-medium hover:gap-4 transition-all">Start a conversation <ArrowUpRight size={16}/></a></Reveal></div></section>
  </main>

  <footer className="border-t border-white/7 py-8"><div className="container flex flex-col md:flex-row gap-4 items-start md:items-center justify-between text-xs text-white/35"><span>© {new Date().getFullYear()} Aviral Verma</span><div className="flex items-center gap-5"><a href={profile.linkedin} target="_blank" rel="noreferrer" className="hover:text-white transition flex items-center gap-1.5"><Linkedin size={14}/> LinkedIn</a><a href={`mailto:${profile.email}`} className="hover:text-white transition flex items-center gap-1.5"><Mail size={14}/> Email</a></div></div></footer>

  <AnimatePresence>{active&&<motion.div className="fixed inset-0 z-50 bg-black/75 backdrop-blur-md p-4 md:p-10 flex items-end md:items-center justify-center" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setActive(null)}><motion.div layoutId={active.id} onClick={e=>e.stopPropagation()} initial={{y:40,opacity:0}} animate={{y:0,opacity:1}} exit={{y:40,opacity:0}} transition={{duration:.35,ease:[.22,1,.36,1]}} className="w-full max-w-4xl max-h-[90vh] overflow-auto bg-[#0b0d10] border border-white/10 rounded-2xl p-7 md:p-10"><div className="flex justify-between gap-6"><div><span className="text-[10px] uppercase tracking-[.18em] text-white/30">{active.number} / Case study</span><h3 className="mt-3 text-3xl md:text-5xl tracking-[-.05em]">{active.name}</h3></div><button aria-label="Close project" onClick={()=>setActive(null)} className="h-10 w-10 shrink-0 rounded-full border border-white/10 flex items-center justify-center hover:bg-white hover:text-black transition"><X size={17}/></button></div><p className="mt-8 max-w-3xl text-lg leading-8 text-white/55">{active.description}</p><div className="mt-10 grid md:grid-cols-2 gap-10"><div><p className="text-[10px] uppercase tracking-[.16em] text-white/30">Problem</p><p className="mt-3 leading-7 text-white/65">{active.problem}</p></div><div><p className="text-[10px] uppercase tracking-[.16em] text-white/30">Technology</p><div className="mt-3 flex flex-wrap gap-2">{active.stack.map(t=><span key={t} className="border border-white/9 rounded-full px-3 py-1.5 text-xs text-white/60">{t}</span>)}</div></div></div><div className="mt-10"><p className="text-[10px] uppercase tracking-[.16em] text-white/30">Key features</p><div className="mt-4 grid sm:grid-cols-2 gap-2">{active.features.map(f=><div key={f} className="border border-white/7 rounded-xl p-4 text-sm text-white/65 flex gap-3"><Check size={15} className="shrink-0 text-white/35 mt-0.5"/>{f}</div>)}</div></div><div className="mt-10 flex flex-wrap gap-3">{active.github?<a href={active.github} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 border border-white/10 rounded-full px-4 py-2.5 text-sm">GitHub <Github size={15}/></a>:<span className="text-xs text-white/30 border border-white/7 rounded-full px-4 py-2.5">GitHub link not supplied in resume</span>}{active.live&&<a href={active.live} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 bg-white text-black rounded-full px-4 py-2.5 text-sm">Live demo <ExternalLink size={15}/></a>}</div></motion.div></motion.div>}</AnimatePresence>
 </>;
}
